name: Ejecutar script de Python

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Ejecutar script de Python
        run: python script.py
